// <auto-generated />
namespace DalToWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmpFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101727436_EmpFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
